version: "3"

services:
  python:
    environment:
      - DJANGO_ENV=production
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=zolaris
      - POSTGRES_PORT=5432
      - DEBUG_ENV = False

  db:
    ports:
      - "5435:5432"  # pointing port 5435 from our environment to postgre default port 5432 in docker
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'zolaris'
      POSTGRES_PORT: 5432