version: "3"

services:
  python:
    environment:
      - DJANGO_ENV=production
      - DEBUG_ENV=False

    env_file:
      - docker_compose_prod.env

  db:
    expose:
      - 5432
    env_file:
      - docker_compose_prod.env

