version: "3"

services:
  python:
    environment:
      - DJANGO_ENV=development
      - DEBUG_ENV=True
    env_file:
      - docker_compose_dev.env

  db:
    expose:
      - 5432
    env_file:
      - docker_compose_dev.env