version: "3"

services:
  python:
    environment:
      - DJANGO_ENV=development
      - DEBUG_ENV=True
      - DOMAIN=dev.zolaris.me-ua.com
      - LETSENCRYPT_EMAIL=vladimir.gumenyuk@gmail.com
    env_file:
      - docker_compose_dev.env

  db:
    expose:
      - 5432
    env_file:
      - docker_compose_dev.env

networks:
    default:
       external:
         name: webproxy