version: "3"

services:
  nginx:
    environment:
      - DOMAIN=dev.zolaris.me-ua.com
      - LETSENCRYPT_EMAIL=vladimir.gumenyuk@gmail.com
      - VIRTUAL_HOST=dev.zolaris.me-ua.com
      - LETSENCRYPT_HOST=dev.zolaris.me-ua.com
  python:
    env_file:
      - docker_compose_dev.env

  db:
    expose:
      - 5432
    env_file:
      - docker_compose_dev.env

networks:
    default:
       external:
         name: webproxy